name: Makefile Python application test with GitHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        make 
    
    - name: Lint with PyLint
      run: |
        make test

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
